app:
  title: Jarvis
  baseUrl: http://localhost:8000
  googleAnalyticsTrackingId: # UA-000000-0

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  database:
    client: postgres
    connection:
      host: localhost
      port: 5432
      user: backstage
      password: backstage
  cors:
    origin: http://localhost:8000
    methods: [GET, OPTIONS, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']

proxy:
  '/jenkins/api':
    target: https://jenkins.se.telenor.net
    headers:
      Authorization:
        $env: JENKINS_BASIC_AUTH_HEADER
  '/sonarqube':
    target: https://sonar.se.telenor.net/api
    allowedMethods: ['GET']
    headers:
      Authorization: 
        $env: SONARQUBE_AUTH_HEADER

sonarQube:
  baseUrl: https://sonar.se.telenor.net

organization:
  name: Telenor Sweden AB

techdocs:
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  requestUrl: http://localhost:7000/api/techdocs
  generators:
    techdocs: 'docker'

sentry:
  organization: my-company

kubernetes:
  serviceLocatorMethod: 'multiTenant'
  clusterLocatorMethods:
    - 'config'
  clusters: []

integrations:
  github:
    - host: https://ghe.gc.telenor.com
      apiBaseUrl: https://ghe.gc.telenor.com/api/v3
      token:
        $env: GITHUB_TOKEN
  
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]

  processors:
    githubOrg:
      providers:
        - target: https://ghe.gc.telenor.com
          apiBaseUrl: https://ghe.gc.telenor.com/api/v3
          token:
            $env: GITHUB_TOKEN

scaffolder:
  github:
    apiBaseUrl: https://ghe.gc.telenor.com/api/v3
    token:
      $env: GITHUB_TOKEN
    visibility: public # or 'internal' or 'private'

auth:
  providers:
    github:
      development:
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET
        enterpriseInstanceUrl: https://ghe.gc.telenor.com
    saml:
      entryPoint: 'http://localhost:7001/'
      issuer: 'passport-saml'
homepage:
  clocks:
    - label: STO
      timezone: 'Europe/Stockholm'