app:
  title: Jarvis
  baseUrl: http://backstage.se.telenor.net
  googleAnalyticsTrackingId: # UA-000000-0

backend:
  baseUrl: http://backstage.se.telenor.net:8080
  listen:
    port: 8080
  database:
    client: postgres
    connection:
      host: 
        $env: POSTGRES_HOST
      port: 
        $env: POSTGRES_PORT
      user: 
        $env: POSTGRES_USERNAME
      password: 
        $env: POSTGRES_PASSWORD
  cors:
    origin: http://backstage.se.telenor.net
    methods: [GET, OPTIONS, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", "data:", "https://ghe.gc.telenor.com"]   

proxy:
  '/jenkins/api':
    target: https://jenkins.se.telenor.net
    headers:
      Authorization:
        $env: JENKINS_BASIC_AUTH_HEADER
  '/sonarqube':
    target: https://sonar.se.telenor.net/api
    allowedMethods: ['GET']
    headers:
      Authorization: 
        $env: SONARQUBE_AUTH_HEADER

sonarQube:
  baseUrl: https://sonar.se.telenor.net

  '/buildkite/api':
    target: https://api.buildkite.com/v2/
    headers:
      Authorization:
        $env: BUILDKITE_TOKEN

organization:
  name: Telenor Sweden AB

techdocs:
  storageUrl: http://backstage.se.telenor.net:8080/api/techdocs/static/docs
  requestUrl: http://backstage.se.telenor.net:8080/api/techdocs
  generators:
    techdocs: local

sentry:
  organization: my-company

kubernetes:
  serviceLocatorMethod: 'multiTenant'
  clusterLocatorMethods:
    - 'config'
  clusters: []

integrations:
  github:
    - host: ghe.gc.telenor.com
      apiBaseUrl: https://ghe.gc.telenor.com/api/v3
      token:
        $env: GITHUB_TOKEN
  
catalog:
  locations: 
    - type: url
      target: https://ghe.gc.telenor.com/TelenorSweden/techdocs-template/blob/master/template.yaml
    - type: url
      target: https://ghe.gc.telenor.com/TelenorSweden/springboot-template/blob/master/template.yaml
  rules:
    - allow: [Component, API, Group, User, Template, Location]

  processors:
    githubOrg:
      providers:
        - target: https://ghe.gc.telenor.com
          apiBaseUrl: https://ghe.gc.telenor.com/api/v3
          token:
            $env: GITHUB_TOKEN

scaffolder:
  github:
    apiBaseUrl: https://ghe.gc.telenor.com/api/v3
    token:
      $env: GITHUB_TOKEN
    visibility: public # or 'internal' or 'private'

auth:
  providers:
    github:
      development:
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET
        enterpriseInstanceUrl: https://ghe.gc.telenor.com
    saml:
      entryPoint: 'http://localhost:7001/'
      issuer: 'passport-saml'
homepage:
  clocks:
    - label: STO
      timezone: 'Europe/Stockholm'