app:
  title: Backstage
  baseUrl: http://backstage.se.telenor.net
  googleAnalyticsTrackingId: # UA-000000-0
backend:
  baseUrl: http://backstage.se.telenor.net:8080
  listen:
    port: 8080
  database:
    client: pg
    connection:
      host: 
        $env: POSTGRES_HOST
      port: 
        $env: POSTGRES_PORT
      user: 
        $env: POSTGRES_USERNAME
      password: 
        $env: POSTGRES_PASSWORD
  cors:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", "data:", "https://ghe.gc.telenor.com"]   
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
proxy:
  '/jenkins/api':
    target: https://jenkins.se.telenor.net
    headers:
      Authorization:
        $env: JENKINS_BASIC_AUTH_HEADER
  '/sonarqube':
    target: https://sonar.se.telenor.net/api
    allowedMethods: ['GET']
    headers:
      Authorization: 
        $env: SONARQUBE_AUTH_HEADER
organization:
  name: My Company
techdocs:
  storageUrl: http://backstage.se.telenor.net:8080/api/techdocs/static/docs
  requestUrl: http://backstage.se.telenor.net:8080/api/techdocs
  generators:
    techdocs: local
sonarQube:
  baseUrl: https://sonar.se.telenor.net
sentry:
  organization: my-company
kubernetes:
  serviceLocatorMethod: 'multiTenant'
  clusterLocatorMethods: 
    - 'config'
  clusters: []
integrations:
  github:
    - host: ghe.gc.telenor.com
      apiBaseUrl: https://ghe.gc.telenor.com/api/v3
      token:
        $env: GITHUB_TOKEN  
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]
  processors:
    githubOrg:
      providers:
        - target: https://ghe.gc.telenor.com
          token:
            $env: GITHUB_TOKEN
scaffolder:
  github:
    token:
      $env: GITHUB_TOKEN
    target: https://ghe.gc.telenor.com
    apiBaseUrl: https://ghe.gc.telenor.com/api/v3
    visibility: public
auth:
  providers:
    github:
      development:
        enterpriseInstanceUrl: https://ghe.gc.telenor.com
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET
costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudDataflow:
      name: Cloud Dataflow
      icon: data
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers
homepage:
  clocks:
    - label: STO
      timezone: 'Europe/Stockholm'